NOSE_TIP_INDEX = 1  # Tip of the nose
CHIN_INDEX = 199  # Chin
LEFT_EYE_INDEX = 33  # Left eye
RIGHT_EYE_INDEX = 263  # Right eye
LEFT_EAR_INDEX = 234  # Left ear
RIGHT_EAR_INDEX = 454  # Right ear
LEFT_MOUTH_CORNER_INDEX = 61  # Left mouth corner
RIGHT_MOUTH_CORNER_INDEX = 291  # Right mouth corner
UPPER_LIP_INDEX = 13  # Upper lip
LOWER_LIP_INDEX = 14  # Lower lip
